
export default {
  INITIALISE_GRID: 'INITIALISE_GRID',
  SET_USER_VALUE: 'SET_USER_VALUE',
  REMOVE_INCORRECT_USER_VALUES: 'REMOVE_INCORRECT_USER_VALUES',
  GAME_WON: 'GAME_WON',
  GAME_RESET: 'GAME_RESET'
}
